# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46f322765f0bbc02e3d65b46d86f86fe9d1b47c67c13f706b5e4a492195c80cc7f14fbacdde306f2385a81bf25a4e0574b418be3a3ca7c658e82215c8e931bed

test:
  secret_key_base: 4905e169e14855ab463fbbe810695e9bbd1deb26d1f40f81fd10021d570b3897fa968eee6647fecaac183bdb36705074b35cd6aef070fe726ddbeb036d38042b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
